[project]
name = "pong"
version = "0.1.0"
description = "Jeu de Pong simple en Python avec Pygame"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "isort>=6.0.1",
    "pygame>=2.6.1",
    "pylint>=3.3.8",
]
